### ISSUE TITLE
Mobile design studies

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/digital-design-ideation#22] opened 2020-04-21 12:07 UTC

**Comment by JennySanchez** [comment] 2020-11-24 22:39
@wonilsuhibm @oliviaflory Can you help by providing a bit more information about the task? 

Such as...
- Objective or the expected outcome of the design studies
- Any existing material to help assignee understand the needs or get started faster?
- Any recommended steps to take?

**Comment by RobertaJHahn** [comment] 2021-04-06 20:51
Closing as the issue is not complete and old.

**Closed by RobertaJHahn** 2021-04-06 20:51 UTC
Labels: Design, Ideation
